
server:
  port: 80
  servlet:
    context-path: 
    encoding:
      charset: UTF-8
      enabled: true
      force: true

upoadDir: /resources
    
spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/adb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 #13.125.117.231    
    username: cos1
    password: green0203
#  mvc hiddenmethod filter enabled : true                       
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    open-in-view: true
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false
      

  jackson:
    serialization:
      fail-on-empty-beans: false


